### ISSUE TITLE
It doesn't hide the default language when another one is selected

### ISSUE THREAD

**Issue by Rumpelcita** [madhenry/tumblr-i18n#1]
I have a tumblr blog with two languages English and Spanish. English is the default language, but when I select Spanish, English language posts remain visible.

Debugging I noticed that the language tag for English only covers the "EN: " instead of "EN:
Text". The other language is selected normally.

What could be the issue?

**Comment by madhenry** [comment]
What kind of options are you using?

The "post content" is regex matched by the  { selector: '.post' } selector setting.
Make sure you have it in your init options with the correct element selector.

```
ti18n.init({
  selector: '.post',
  langs: {
    'es': 'SPA',
    'en': 'ENG'
  },
  defaultLang: 'es'
});
```

**Comment by Rumpelcita** [comment]
This are my options. Spanish shows and hides okay, but English is always visible, menus translate fine.

```
            $(function() {
              ti18n.init({
                langs: {
                  'en': 'EN',
                  'es': 'ES'
                },
                defaultLang: 'en',
                selector: '.posts',
                translations: resources
              }, function( activeLang ) {
                console.log( 'This is the automatically active language key:',                             activeLang );
              });

            });
```

**Comment by Rumpelcita** [comment]
I solved the issue by adding a <span> tag between each language. The tag covers the language label and the post content.
